### ISSUE TITLE
Use tox and run different versions of tests in parallel

### ISSUE THREAD

**Issue by danslimmon** [exosite-labs/pyonep#28]
These are two separate things. tox is good at isolating different versions from one another, but it doesn't do parallelism. I think what I'll probably do is write a bash script that loops over the desired versions and toxes each with a & into a log file, then reports any faliures at the end.

**Comment by hashar** [comment]
Alternatively, you could go with `detox` which wraps around `tox` and runs env in parallel https://pypi.python.org/pypi/detox/ :D
